name: CI

on:
  push:
    paths:
      - "problems/**"
  pull_request:
    paths:
      - "problems/**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          architecture: x64
      - name: Determine changed problems
        id: changed_problems
        run: |
          echo "${{ steps.changed_problems.outputs.modified }}"

      - name: Build and run tests
        run: |
          for problem in ${{ steps.changed_problems.modified }}; do
            cd "problems/$problem"
            javac Test.java
            java Test
            cd ../..
          done
