name: CI

on:
  push:
    paths:
      - "problems/**"
  pull_request:
    paths:
      - "problems/**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          architecture: x64
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if ["$file" == problems/* ] && [ "$file" == *.java ]; then
              echo "$file"
            fi
          done
